<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProvinceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::beginTransaction();
        try {
            DB::table('provinces')->insert([
                ['name' => 'Almería', 'community_id' => 1,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Cádiz', 'community_id' => 1,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Córdoba', 'community_id' => 1,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Granada', 'community_id' => 1,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Huelva', 'community_id' => 1,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Jaén', 'community_id' => 1,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Málaga', 'community_id' => 1,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Sevilla', 'community_id' => 1,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Huesca', 'community_id' => 2,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Teruel', 'community_id' => 2,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Zaragoza', 'community_id' => 2,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Oviedo', 'community_id' => 3,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Palma de Mallorca', 'community_id' => 4,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Las Palmas de Gran Canaria', 'community_id' => 5,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Santa Cruz de Tenerife', 'community_id' => 6,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Santander', 'community_id' => 6,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Albacete', 'community_id' => 7,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Ciudad Real', 'community_id' => 7,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Cuenca', 'community_id' => 7,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Guadalajara', 'community_id' => 7,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Toledo', 'community_id' => 7,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Ávila', 'community_id' => 8,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Burgos', 'community_id' => 8,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'León', 'community_id' => 8,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Salamanca', 'community_id' => 8,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Segovia', 'community_id' => 8,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Soria', 'community_id' => 8,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Valladolid', 'community_id' => 8,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Zamora', 'community_id' => 8,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Barcelona', 'community_id' => 9,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Gerona', 'community_id' => 9,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Lérida', 'community_id' => 9,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Tarragona', 'community_id' => 9,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Alicante', 'community_id' => 10,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Castellón', 'community_id' => 10,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Valencia', 'community_id' => 10,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Badajoz', 'community_id' => 11,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Cáceres', 'community_id' => 11,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'La Coruña', 'community_id' => 12,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Lugo', 'community_id' => 12,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Orense', 'community_id' => 13,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Pontevedra', 'community_id' => 13,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Madrid', 'community_id' => 14,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Murcia', 'community_id' => 14,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Pamplona', 'community_id' => 15,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Bilbao', 'community_id' => 16,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'San Sebastián', 'community_id' => 16,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Vitoria', 'community_id' => 16,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()],
                ['name' => 'Logroño', 'community_id' => 17,
                    'created_at' => \Carbon\Carbon::now(),
                    'updated_at' => \Carbon\Carbon::now()]
            ]);
            DB::commit();
        }catch(\Exception $exception) {
            DB::rollBack();
        }
    }
}
